package sqltote

var (
	// Extra is generated by tote.  Do not modify.
	Extra = struct {
		Insert      string
		QueryAll    string
		QueryBySlug string
	}{
		`INSERT INTO post (slug, title, created, markdown, html)
VALUES (?, ?, ?, ?, ?)`,
		`SELECT *
FROM post`,
		`SELECT id, slug, title, created, markdown, html
FROM post
WHERE slug = ?`,
	}
)
